"""Run the full empirical study and write result tables.

Computes every test across the paper windows and the out-of-sample extension,
writes tidy CSVs to ``output/tables/`` and a human-readable ``output/RESULTS.md``,
and prints a console summary. Safe to run repeatedly (data is cached locally).

    python scripts/run_study.py
"""

from __future__ import annotations

import sys
import warnings
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
warnings.filterwarnings("ignore")

import pandas as pd  # noqa: E402

from capm.empirics import (  # noqa: E402
    betting_against_beta,
    factor_premia,
    grs_panel,
    momentum_study,
    security_market_line,
    sorted_decile_study,
)

TABLES = ROOT / "output" / "tables"
PCT = 100.0


def _pct(x: float) -> float:
    return round(x * PCT, 2)


def main() -> None:
    TABLES.mkdir(parents=True, exist_ok=True)
    lines: list[str] = ["# Results\n",
                        "Generated by `scripts/run_study.py`. Returns/premiums are annualized, "
                        "in percent. t-statistics use Newey-West (HAC) standard errors.\n"]

    # ---- Factor premiums -------------------------------------------------- #
    lines.append("\n## Factor premiums\n")
    for period in ["paper_1927_2003", "modern_2004_now", "full"]:
        prem = factor_premia(period)
        out = prem.copy()
        out[["mean_ann", "vol_ann", "sharpe_ann"]] = out[["mean_ann", "vol_ann", "sharpe_ann"]]
        out.to_csv(TABLES / f"factor_premia_{period}.csv")
        show = pd.DataFrame({
            "Premium %/yr": (prem["mean_ann"] * PCT).round(2),
            "Vol %/yr": (prem["vol_ann"] * PCT).round(1),
            "t-stat": prem["t_stat"].round(2),
            "Sharpe": prem["sharpe_ann"].round(2),
            "Months": prem["n_months"].astype(int),
        })
        lines.append(f"\n**{period}**\n\n{show.to_markdown()}\n")

    # ---- Flat SML --------------------------------------------------------- #
    lines.append("\n## The flat Security Market Line\n")
    sml_rows = []
    for period in ["paper_1963_2003", "modern_2004_now"]:
        s = security_market_line(period)
        sml_rows.append({
            "period": period,
            "CAPM slope %/yr": _pct(s.capm_slope_ann),
            "realized slope %/yr": _pct(s.realized_slope_ann),
            "FM slope %/yr": _pct(s.fm_slope_ann),
            "FM slope t": round(s.fm_slope_t, 2),
            "FM intercept %/yr": _pct(s.fm_intercept_ann),
            "FM intercept t": round(s.fm_intercept_t, 2),
            "FM n_assets": s.fm_n_assets,
        })
    sml_df = pd.DataFrame(sml_rows).set_index("period")
    sml_df.to_csv(TABLES / "sml_summary.csv")
    lines.append(f"\n{sml_df.T.to_markdown()}\n")
    lines.append("\n*The CAPM predicts the cross-sectional slope on beta should equal the "
                 "average excess market return and the intercept should be zero. Instead the "
                 "slope is flat (near zero) and the intercept is large and positive.*\n")

    # ---- Decile sorts ----------------------------------------------------- #
    lines.append("\n## Decile sorts (CAPM cannot explain the spreads)\n")
    spread_rows = []
    sort_specs = [("beme", True, "paper_1963_2003"), ("me", False, "paper_1963_2003"),
                  ("momentum", True, "paper_1963_2003"),
                  ("beme", True, "modern_2004_now"), ("me", False, "modern_2004_now")]
    for kind, lms, period in sort_specs:
        study = sorted_decile_study(kind, period, long_minus_short=lms)
        study.table.to_csv(TABLES / f"decile_{kind}_{period}.csv")
        spread_rows.append({
            "sort": study.label,
            "period": period,
            "spread": study.spread_label,
            "mean %/yr": _pct(study.spread_mean_ann),
            "CAPM alpha %/yr": _pct(study.spread_alpha_ann),
            "alpha t": round(study.spread_alpha_t, 2),
            "spread beta": round(study.spread_beta, 2),
        })
    spread_df = pd.DataFrame(spread_rows)
    spread_df.to_csv(TABLES / "spreads.csv", index=False)
    lines.append(f"\n{spread_df.to_markdown(index=False)}\n")

    # ---- GRS panel -------------------------------------------------------- #
    lines.append("\n## GRS joint test of zero alphas\n")
    for period in ["paper_1963_2003", "modern_2004_now"]:
        panel = grs_panel(period)
        panel.to_csv(TABLES / f"grs_panel_{period}.csv", index=False)
        show = panel.copy()
        show["mean_abs_alpha_%/yr"] = (show["mean_abs_alpha_ann"] * PCT).round(2)
        show["grs_F"] = show["grs_F"].round(2)
        show["p_value"] = show["p_value"].round(4)
        show = show[["test_assets", "model", "n_assets", "grs_F", "p_value", "rejects_5pct", "mean_abs_alpha_%/yr"]]
        lines.append(f"\n**{period}**\n\n{show.to_markdown(index=False)}\n")

    # ---- Momentum --------------------------------------------------------- #
    lines.append("\n## Momentum vs the models\n")
    m = momentum_study("paper_1963_2003")
    mom_df = pd.DataFrame({
        "metric": ["WML mean %/yr", "WML CAPM alpha %/yr (t)", "WML FF3 alpha %/yr (t)"],
        "value": [f"{_pct(m.wml_mean_ann)}",
                  f"{_pct(m.wml_capm_alpha_ann)} (t={m.wml_capm_alpha_t:.1f})",
                  f"{_pct(m.wml_ff3_alpha_ann)} (t={m.wml_ff3_alpha_t:.1f})"],
    })
    mom_df.to_csv(TABLES / "momentum.csv", index=False)
    lines.append(f"\n{mom_df.to_markdown(index=False)}\n")

    # ---- BAB -------------------------------------------------------------- #
    lines.append("\n## Betting Against Beta (tradeable consequence of the flat SML)\n")
    bab_rows = []
    for period in ["full", "modern_2004_now"]:
        b = betting_against_beta(period)
        bab_rows.append({
            "period": period,
            "ann return %": _pct(b.metrics.ann_return),
            "ann vol %": _pct(b.metrics.ann_vol),
            "Sharpe": round(b.metrics.sharpe, 2),
            "max drawdown %": _pct(b.metrics.max_drawdown),
            "CAPM alpha %/yr": _pct(b.capm_alpha_ann),
            "alpha t": round(b.capm_alpha_t, 2),
            "CAPM beta": round(b.capm_beta, 2),
        })
    bab_df = pd.DataFrame(bab_rows).set_index("period")
    bab_df.to_csv(TABLES / "bab_metrics.csv")
    lines.append(f"\n{bab_df.T.to_markdown()}\n")

    (ROOT / "output" / "RESULTS.md").write_text("\n".join(lines), encoding="utf-8")
    print("Wrote tables to", TABLES)
    print("Wrote", ROOT / "output" / "RESULTS.md")
    print("\n=== Key numbers ===")
    print(sml_df.T.to_string())
    print(bab_df.T.to_string())


if __name__ == "__main__":
    main()
